source: https://github.com/kalkantech/devops-app-config.git
release:
namespace: argocd

applications:
  - name: devops-next-app
    enabled: true
    source_path: "apps/devops-next-app"
    source_ref: HEAD
    values:
      appNamespace: devops-test-app
