source: https://github.com/kalkantech/devops-app-config.git
release: "devops-apps"
applications:
  - name: devops-apps
    enabled: true
    release: "devops-apps"
    source_path: "."
    source_ref: HEAD
    helm_values:
      - argo-apps/values.yaml
