apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-next-app.fullname" . }}
  namespace: {{ .Values.appNamespace }}
  labels:
    {{- include "devops-next-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .name }}
    {{- include "devops-next-app.selectorLabels" . | nindent 4 }}
